version: '3'
services:
  database:
    image: 'mysql'
    volumes:
      - "/home/kunal/mysql:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root123
    ports:
      - "3306:3306"
  auth-service:
    build: ./backend
    restart: on-failure
    ports:
      - "8081:8081"
    environment:
      - MYSQL_USER=root
      - MYSQL_HOST=database
      - MYSQL_PASSWORD=root123
      - DATABASE=test
      - DB_DIALECT=mysql
      - PORT=8081
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    restart: on-failure
    volumes:
      - app/node_modules
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=auth-service